### ISSUE TITLE
issue_number is ignored

### ISSUE THREAD

**Issue by glureau** [izhangzhihao/delete-comment#32]
From logs, looks like the issue_number is the correct one, but it actually remove comments from another PR.

![image](https://user-images.githubusercontent.com/7968075/141016150-99799a33-d3ec-4e5a-bf5a-24f7b9267eed.png)

**Comment by izhangzhihao** [comment]
Might be because of https://github.com/izhangzhihao/delete-comment/blob/764ede2d6d7e6ab313a0442ac1978474149aa4ff/src/main.ts#L46

**Comment by glureau** [comment]
Thanks for your work and your quick response!

As I was trying to have only one comment from my bot, and remove the previous one, I found another project doing that directly : https://github.com/marketplace/actions/sticky-pull-request-comment
Maybe it's handling the delete properly there if you're interested.

**Comment by apomalyn** [comment]
Finally fixed with #35 (and #34)
